# Generated by Django 5.0.2 on 2024-02-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_customuser_otptoken_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
