# Generated by Django 5.0.2 on 2024-02-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c61cf3', max_length=6),
        ),
    ]
