# Generated by Django 5.0.3 on 2024-03-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
